version: "3.8"

services:
  base_api:
    build:
      context: ./
      dockerfile: ./deploy/app/base/Dockerfile
    command: make run_dev
    container_name: base_api
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./deploy/nginx/
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - base_api

volumes:
  postgres_data:
