"""add field public key

Revision ID: 21f0f20e9bba
Revises: 87d79cc9e70b
Create Date: 2023-07-04 12:45:38.164513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f0f20e9bba'
down_revision = '87d79cc9e70b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('public_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'wallet', ['public_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='unique')
    op.drop_column('wallet', 'public_key')
    # ### end Alembic commands ###
