"""add awllet to transaction model

Revision ID: 3eae1e681fcf
Revises: 42d35ab89340
Create Date: 2023-07-03 07:43:43.480917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eae1e681fcf'
down_revision = '42d35ab89340'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('wallet', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'wallet')
    # ### end Alembic commands ###
