"""change unique for mnemonic

Revision ID: d46f71954db0
Revises: 75c65942a949
Create Date: 2023-07-02 08:00:35.279192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd46f71954db0'
down_revision = '75c65942a949'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wallet_mnemonic_key', 'wallet', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('wallet_mnemonic_key', 'wallet', ['mnemonic'])
    # ### end Alembic commands ###
