"""created some models

Revision ID: f969aba9110a
Revises: d75e5550c845
Create Date: 2023-07-01 20:49:43.334106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f969aba9110a'
down_revision = 'd75e5550c845'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('public_key', sa.String(), nullable=True))
    op.add_column('wallet', sa.Column('privet_key', sa.String(), nullable=True))
    op.add_column('wallet', sa.Column('mnemonic', sa.String(), nullable=True))
    op.add_column('wallet', sa.Column('parent_wallet', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'wallet', ['mnemonic'])
    op.create_unique_constraint(None, 'wallet', ['public_key'])
    op.create_unique_constraint(None, 'wallet', ['privet_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='unique')
    op.drop_constraint(None, 'wallet', type_='unique')
    op.drop_constraint(None, 'wallet', type_='unique')
    op.drop_column('wallet', 'parent_wallet')
    op.drop_column('wallet', 'mnemonic')
    op.drop_column('wallet', 'privet_key')
    op.drop_column('wallet', 'public_key')
    # ### end Alembic commands ###
